### ISSUE TITLE
New Token submission - IoTexShiba

### ISSUE THREAD

**Issue by IoTexShiba** [iotubeproject/ioTube#103]
# ioTube Token submission

Please read the token submission guide here: https://docs.iotube.org/introduction/token-submission

## Team / Developer name
IoTexShiba

## Token Symbol
IoShib

## Token Decimals
9 

## Token Name in full
IoTexShiba

## Link to the token icon
https://www.iotexshiba.io/wp-content/uploads/2021/11/logoioshib200.png

## Short description of your project
IoTeX Shiba is a community driven and owned meme project builded on the IoTeX ecosystem. We're developing passive income opportunities for our holders.

## What is the blockchain (source blockchain) that your token is issued on

* [ ] Ethereum  
* [ ] Binance Smart Chain
* [ ] Polygon
* [x] IoTeX

## What blockchains (destination blockchain) would you like your token is bridged to

* [ ] Ethereum  
* [ ] Binance Smart Chain
* [x] Polygon
* [ ] IoTeX

(Please check https://docs.iotube.org/introduction/token-submission#integration-fee for integration fees of different blockchains)

## Token native contract address explorer link

https://iotexscan.io/tx/0xe77a2d7491ac875d86b9975ce43d68c6f1336b00e22249eb8670609248840cdd

Address: 

## Your project websites

- https://www.iotexshiba.io/

## Your social channels

- Telegram: https://t.me/iotexshiba
- Twitter: https://twitter.com/IoTexShiba
- Discord:

## Verification of the token

Please provide the verification of your token in one of the following ways.

* [ ] Token address on your website. Please specify the link.
* [X] CMC / Coingecko profile link with token contract address and link to website/social

https://www.coingecko.com/de/munze/iotexshiba

## Send test tokens 

Please send a few test tokens ($1-$10 worth) to our wallet address: `0x571e603e3B5c82Bd40998C538603dF4fb42bB051`.

https://iotexscan.io/tx/0xe77a2d7491ac875d86b9975ce43d68c6f1336b00e22249eb8670609248840cdd

## Integration fee 

Please send the payment to `0x571e603e3B5c82Bd40998C538603dF4fb42bB051` or `io12u0xq03mtjpt6sye33fcvq7lf76zhvz3yvt8q0` and post your txn link here.

https://iotexscan.io/tx/0x989047187487eae46bbf17a6d97363ff56f841e7c23b1e3756018d70b360c4f8

**Comment by IoTexShiba** [comment]
hey @guo we would like to create the crosschain ioshib token. However, we have the tax fee on it of 4% on every tx and our contract is renounced, so we can't exclude anyone. Is this a problem? I don't think so, but maybe you could double check. Once you confirmed to me, that it's no problem, I'll send the BNB and matic fees for the bridge contracts.

**Comment by IoTexShiba** [comment]
@guo integration fee for matic paid now. We'll just do the matic bridge for now and extend later.

**Comment by guo** [comment]
Cool. I will check if the tax is a concern. And will start the integration asap.

**Comment by guo** [comment]
@IoTexShiba , please confirm the contact address is https://iotexscan.io/token/0x3ea683354bf8d359cd9ec6e08b5aec291d71d880?format=0x

Thank you.

**Comment by IoTexShiba** [comment]
> @IoTexShiba , please confirm the contact address is https://iotexscan.io/token/0x3ea683354bf8d359cd9ec6e08b5aec291d71d880?format=0x
> 
> Thank you.

Yes this is correct.

Name for token:

Crosschain Shiba
cShiba

Would that be possible? Thanks a lot.

**Comment by guo** [comment]
Crosschain Shiba
cShiba

is OK. 

You mean on Polygon, right？

**Comment by guo** [comment]
could you please ping me on telegram? @qevanguo. there is a concern about the 4% tax support.

**Comment by IoTexShiba** [comment]
> Crosschain Shiba cShiba
> 
> is OK.
> 
> You mean on Polygon, right？

yes, but also the bridge contract token on iotex.

**Comment by IoTexShiba** [comment]
> could you please ping me on telegram? @qevanguo. there is a concern about the 4% tax support.

I dm you on telegram: I know, that the bridge smart contract will recieve tax rewards and they won't be accessible anymore. That's ok. The reflections received by the contract would be essentially burned tokens.
