### ISSUE TITLE
New Token submission - Cartesi - CTSI

### ISSUE THREAD

**Issue by colinsteil** [iotubeproject/ioTube#156]
# ioTube Token submission

Please read the token submission guide here: https://docs.iotube.org/introduction/token-submission

## Team / Developer name

Cartesi

## Token Symbol

CTSI

## Token Decimals

18

## Token Name in full

Cartesi Token

## Link to the token icon

https://drive.google.com/file/d/1ypeGTA6wThgp2uivXFGuPMQFmIxbzuLL/view?usp=sharing

## Short description of your project

[Cartesi - The Blockchain OS](https://cartesi.io/) is a decentralized Layer-2 infrastructure that supports Linux and mainstream software components. For the first time, developers can code scalable smart contracts with rich software tools, libraries, and the services they’re used to, bridging the gap between mainstream software and blockchain.

Cartesi is enabling millions of new startups and their developers to use The Blockchain OS and bring Linux applications on board. With a [groundbreaking virtual machines](https://cartesi.io/en/docs/machine/intro/) and[optimistic rollups](https://medium.com/cartesi/scalable-smart-contracts-on-ethereum-built-with-mainstream-software-stacks-8ad6f8f17997), Cartesi paves the way for developers of all kinds, to build the next generation of blockchain apps.

Welcome to The Blockchain OS, home to what’s next.

## What is the blockchain (source blockchain) that your token is issued on

* [x] Ethereum  

## What blockchains (destination blockchain) would you like your token is bridged to

* [x] IoTeX

(Please check https://docs.iotube.org/introduction/token-submission#integration-fee for integration fees of different blockchains)

## Token native contract address explorer link

https://etherscan.io/token/0x491604c0FDF08347Dd1fa4Ee062a822A5DD06B5D

## Your project websites

- https://cartesi.io

## Your social channels

- Telegram: https://t.me/CartesiProject
- Twitter: https://twitter.com/cartesiproject
- Discord: https://discordapp.com/invite/Pt2NrnS

## Verification of the token

Please provide the verification of your token in one of the following ways.

* [x ] CMC / Coingecko profile link with token contract address and link to website/social
* https://coinmarketcap.com/currencies/cartesi/
* https://www.coingecko.com/en/coins/cartesi

## Send test tokens 

Please send a few test tokens ($1-$10 worth) to our wallet address: `0x571e603e3B5c82Bd40998C538603dF4fb42bB051`.

https://etherscan.io/tx/0xc1c61207b5e2830b5b89e94d228ab174b7683f4ce8570c16f509d8eb555577fd

## Integration fee 

Please send the payment to `0x571e603e3B5c82Bd40998C538603dF4fb42bB051` or `io12u0xq03mtjpt6sye33fcvq7lf76zhvz3yvt8q0` and post your txn link here.

https://etherscan.io/tx/0xeafc94047e055de75f338450d5aadbaf6bcf2a0f20bea6ce643815014fc7ec02

**Comment by guo** [comment]
- [ ] deploy tokens
ETH contracts: 0x30e68fACB9D4E04FEdc12A8Cc539639f90F40c63
IOTEX contracts: 0xD7649962EABff74D3277FB990f23dD0ae6c355F6 (io16ajfjch2hlm56vnhlwvs7g7aptnvx40ksyvrz5)
- [ ] add to validator list
- [ ] add to website
- [ ] test transfer

**Comment by guo** [comment]
done. thanks!
