### ISSUE TITLE
Some txn in ioTube got stuck between BSC <-> IoTeX

### ISSUE THREAD

**Issue by guo** [iotubeproject/ioTube#17]
There are some txn in ioTube stuck between BSC and IoTeX. We have identified this issue. BSC API server was not stable and some txns were not returned by the server. As a result, they are not seen by certain witnesses by ioTube. 

Currently, all witnesses are re-running their service to get all txs confirmed. 

If you have any txns that are not settled by ioTube. Please comment below. We will take a look after witnesses are up to height.

**Comment by kaconk69** [comment]
https://bscscan.com/tx/0x3230e90a06d82dc4f67b6811c38d4190a44948b63500b7eea8667e302b89ce71

destination: io143feslzxqlv7tkymfel27dz3mg7y9268mhucpc

**Comment by kaconk69** [comment]
again
https://bscscan.com/tx/0xcac312d67e38d1c02566365b61e17bcbdaac3e36357a6f7eddbf475245d2a266

**Comment by fifaxyj** [comment]
https://bscscan.com/tx/0x1b5fd376d3b52e826e8d0119672c84fb67dfd5df577fa9009844619e0a855f9b

destination
io1x3h6te2r57r5ag259gcr3mpxfdsgr9747qdz2a

**Comment by guo** [comment]
> https://bscscan.com/tx/0x3230e90a06d82dc4f67b6811c38d4190a44948b63500b7eea8667e302b89ce71
> 
> destination: io143feslzxqlv7tkymfel27dz3mg7y9268mhucpc

arrived here: https://iotexscan.io/action/5ba6e406ae1840caeb7f2805b4e6e49e13561c80124e17a5396b89aea3485dbd

**Comment by guo** [comment]
> again
> https://bscscan.com/tx/0xcac312d67e38d1c02566365b61e17bcbdaac3e36357a6f7eddbf475245d2a266

here: https://iotexscan.io/action/0efaae47121d1a5e4337badb2f47e040a56e3775047d5d4c6d4e4e568e533d92
