### ISSUE TITLE
Transhuman Coin 

### ISSUE THREAD

**Issue by gemsbokgroup** [iotubeproject/ioTube#183]
# TRANSHUMAN COIN Token submission for iotube

Please read the token submission guide here: https://docs.iotube.org/introduction/token-submission

## Team / Developer name
CEO & Founder: Dr. Charles Awuzie - www.facebook.com/reformed.charles.awuzie | https://www.linkedin.com/in/drcharlesawuzie
Co-founder: Peter Xing - https://www.linkedin.com/in/peter-xing
Co-founder: Alyse Sue - https://www.linkedin.com/in/alysesue
...

## Token Symbol
THC
...

## Token Decimals
9
... 

## Token Name in full
TRANSHUMAN COIN
...

## Link to the token icon
https://transhumancoin.finance/thclogo.jpg

## Short description of your project

We started as a meme coin for the Transhumanism movement - a community of over 2 million Scientists and Technologists around the world. Then we started building utilities. We built P2P Exchange - p2p.valid.finance and also in the process of announcing our DeFi trading tool platform - [valid.finance which is currently registered in the UK.](https://find-and-update.company-information.service.gov.uk/company/14817431/officers)

Who are we? Transhuman Coin is a Research oriented BEP20 token merging Biotech & Artificial Intelligence in the metaverse with the aims of using technology to solve ageing, diseases and improve longevity.

Transhumanism is the ideology of enhancing human life through Science & Tech. As a project dedicated to Human Enhancement, we fund Advanced BioTech Projects, Assistive Technologies, Research on Anti Ageing etc. THC is also the native token of valid.finance and p2p.valid.finance

We are building Decentralized Labs in the metaverse & our [E-shop](https://www.transhumancoin.finance/shop) will accept our token in exchange for medical supplies. Our Smart Contract is [audited by Techrate. https://github.com/TechRate/Smart-Contract-Audits/blob/main/November/Transhuman%20Coin%20Full%20Smart%20Contract%20Security%20Audit.pdf

WE ARE BUILDING A HEALTH dAPP on [IOTEX BLOCKCHAIN.https://community.iotex.io/t/accepted-transhumancoin/8941

Transhuman Coin is the first and only token dedicated to Transhumanism and fastly becoming the major currency of transaction in Transhumanism communities globally. We are governed by a [Board of Scientific Advisors]( https://www.youtube.com/watch?v=Ce1fbEGZI3E ) who meet regularly to provide leadership for the project. You too can join this board if you have the right amount of THC required."

## What is the blockchain (source blockchain) that your token is issued on

* [ ] Binance Smart Chain

## What blockchains (destination blockchain) would you like your token is bridged to

* [ ] IoTeX

(Please check https://docs.iotube.org/introduction/token-submission#integration-fee for integration fees of different blockchains)

## Token native contract address explorer link

Address: https://bscscan.com/address/0x56083560594E314b5cDd1680eC6a493bb851BBd8

## Your project websites

- https://www.transhumancoin.finance

## Your social channels

- Telegram: https://t.me/buytranshumancoin
- Twitter: htpps://www.twitter.com/transhumancoin
- Facebook: https://www.facebook.com/transhumancoin

## Verification of the token

Please provide the verification of your token in one of the following ways.

* [ www.transhumancoin.finance - you will find the token address and cmc page] Token address on your website. Please specify the link.
* [ ] CMC / Coingecko profile link with token contract address and link to website/social - https://coinmarketcap.com/currencies/transhuman-coin/
https://www.coingecko.com/en/coins/transhuman-coin

## Send test tokens 

Please send a few test tokens ($1-$10 worth) to our wallet address: `0x571e603e3B5c82Bd40998C538603dF4fb42bB051`.

PAID:  https://bscscan.com/tx/0x1edb95ffd060e9a7493631a801dfd587e315cf631fa50663e07c6ff00ac87115

## Integration fee 

Please send the payment to `0x571e603e3B5c82Bd40998C538603dF4fb42bB051` or `io12u0xq03mtjpt6sye33fcvq7lf76zhvz3yvt8q0` and post your txn link here.

PAID:   https://bscscan.com/tx/0x3c3392856e583be7c8cdce4767ccc1f50525275ffaea4787dbc215ef9e688be1

**Comment by guo** [comment]
ioTube does not support tax-based token yet. That requires additional work and time. (We are still investigating the feasibility now.)

**Comment by gemsbokgroup** [comment]
Hi guo, thanks for the response. What if iotube's contract address is whitelisted by us, that way transactions done on iotube are tax free? this has worked in our other integrations - including cex and swft blockchain. we are a project of interest for Raullen and it is important that we bridge to iotex asap. thanks once again Guo.

**Comment by guo** [comment]
also, please note that the crosschain token on iotex will not have tax feature like on BSC.

**Comment by gemsbokgroup** [comment]
Yes, we understand that the crosschain token on iotex will not have the current tax feature. 
Some interesting update: We are being featured in the CMC KillerwhalesTV show and one of our core pitch includes our iotex proposal. We have mentioned that we are bridging using iotube to the organisers and will like to know the time frame for the bridge? 
Looking forward to a THC on iotex via iotube. Thanks!

**Comment by CoderZhi** [comment]
@guo Here is the CTHC generated on BSC: https://bscscan.com/address/0x8dfb1099c53f634becf3c98ae19eb1baa1b37d43

**Comment by gemsbokgroup** [comment]
Thanks @guo .

**Comment by guo** [comment]
@gemsbokgroup have you whitelisted this address?

**Comment by gemsbokgroup** [comment]
Yes - now whitelisted on tx: https://bscscan.com/tx/0x60fe1d1080c5911669f1c5bdcadd9056523debf8cd0e7b951470707965025fb5

**Comment by guo** [comment]
deployed crosschain token on iotex: 0xB4CBD308e879C0C3a3a996ad6c7576B123a506f4.

**Comment by CoderZhi** [comment]
@gemsbokgroup could you also whitelist https://bscscan.com/address/0x2a26fede01bfa03e65cd3c68f421cab83648391a#code, which will enable the direct deposit of THC? After that, you may try on https://web-iotube-org-pr-183.onrender.com/tube by yourself. Be aware that there are fees when you transfer from IoTeX to BSC.

**Comment by gemsbokgroup** [comment]
Thanks. The address is now whitelisted - https://bscscan.com/tx/0x2fb93d2b9926cf69dc45fb1889e0e434597cb85b12a2bc64705137c4005ab756 . And i successfully swapped 100000 THC to CTHC. Thanks.

**Comment by guo** [comment]
you can try to bridge token's to iotex too.

I have tested. Both THC and CTHC can be bridged to iotex now. I am going to
merge the front end change if you don't see any issues.

**Comment by guo** [comment]
launched on ioTube now. Closing task.

**Comment by gemsbokgroup** [comment]
Thanks @guo . We could connect further on telegram - t.me/gemsbokgroup

Looking forward to more collaborations in the IoTex ecosystem. Cheers.
