### ISSUE TITLE
New Token submission - IoTexShiba

### ISSUE THREAD

**Issue by IoTexShiba** [iotubeproject/ioTube#184]
# ioTube Token submission

Please read the token submission guide here: https://docs.iotube.org/introduction/token-submission

## Team / Developer name
Mike Landen

## Token Symbol
IOSHIB

## Token Decimals
9

## Token Name in full
IoTexShiba

## Link to the token icon
https://www.iotexshiba.io/wp-content/uploads/2021/11/logoioshib200.png

## Short description of your project
First Meme Token on the IoTex Blockchain

## What is the blockchain (source blockchain) that your token is issued on

* [ ] Ethereum  
* [ ] Binance Smart Chain
* [ ] Polygon
* [x] IoTeX

## What blockchains (destination blockchain) would you like your token is bridged to

* [x] Ethereum  
* [x] Binance Smart Chain
* [x] Polygon
* [ ] IoTeX

(Please check https://docs.iotube.org/introduction/token-submission#integration-fee for integration fees of different blockchains)

## Token native contract address explorer link

Address: https://iotexscan.io/token/0x3ea683354bf8d359cd9ec6e08b5aec291d71d880

## Your project websites

- https://www.iotexshiba.io/

## Your social channels

- Telegram: https://t.me/iotexshiba
- Twitter: https://twitter.com/IoTexShiba
- Discord: https://discord.gg/qG8CK3nahM

## Verification of the token

Please provide the verification of your token in one of the following ways.

* [ ] Token address on your website. Please specify the link.
* [x] CMC / Coingecko profile link with token contract address and link to website/social

https://www.coingecko.com/en/coins/iotexshiba
https://coinmarketcap.com/currencies/iotexshiba/

## Send test tokens 

Please send a few test tokens ($1-$10 worth) to our wallet address: `0x571e603e3B5c82Bd40998C538603dF4fb42bB051`.

## Integration fee 

Please send the payment to `0x571e603e3B5c82Bd40998C538603dF4fb42bB051` or `io12u0xq03mtjpt6sye33fcvq7lf76zhvz3yvt8q0` and post your txn link here.

**Comment by IoTexShiba** [comment]
Considerations:

IoTexShiba Smart Contract is tax based contract and renounced.
Bridge locker can't be excluded from recieving reflections. These reflections can be considered as burned.
Bridge contract is excluded from fees as smart contracts in general are excluded from fee structure.
All bridge contracts can be deployed as default ERC20 contracts, they don't have to include tax system.
This means they will behave as normal ERC20 tokens on the bridge side.

There is no requirement to include the TAX feature into the bridge contracts.

**Comment by IoTexShiba** [comment]
TX for 1.000.000 IOSHIB Test Tokens:

https://iotexscan.io/tx/0xc1b3213daf1ad6a934524a0f76b6dc4ae61b6a9c02de143b3b38ad8d19e4d658

**Comment by IoTexShiba** [comment]
I checked your docu for crosschained tokens here: https://docs.iotube.org/introduction/token-submission/special-need-of-crosschained-token

But I can't find the CrossChainERC20.sol contract. Can you provide link? I can check and find out if its possible to deploy a modified bridge contract.

**Comment by IoTexShiba** [comment]
Once you confirmed, you can complete the integration for us, we'll submit the integration-fee for all 3 blockchains. Can we send the funds via iotex blockchain? or do they have to be sent on native chain?

**Comment by guo** [comment]
Yes. please wait for our confirmation first.

**Comment by CoderZhi** [comment]
> Considerations:
> 
> * IoTexShiba Smart Contract is tax based contract and renounced.
> * Bridge locker can't be excluded from recieving reflections. These reflections can be considered as burned.
> * Bridge contract is excluded from fees as smart contracts in general are excluded from fee structure.
> * All bridge contracts can be deployed as default ERC20 contracts, they don't have to include tax system.
> 
> This means they will behave as normal ERC20 tokens on the bridge side. There is no requirement to include the TAX feature into the bridge contracts.

Correct me for the following statements:
1. No tax will be charged if recipient is bridge contract
2. Tax will be charged if sender is bridge contract and the recipient is not a contract
3. Tax will not be charged if sender is bridge contract and the recipient is a contract

Could you also help provide some tx examples with contract sender/recipient?

**Comment by IoTexShiba** [comment]
1. No tax will be charged if recipient is bridge contract **-> this is wrong, tax is charged if someone sends to bridge contract. This is a normal transaction and should be charged.**

2. Tax will be charged if sender is bridge contract and the recipient is not a contract **-> this is wrong. We noticed, that if SENDER is smart contract, there is no charge. See here: our Multisig Smart Contract send 50 ioshib to an address and got no tax charge (Multisig smart contract is NOT EXCLUDED).**

https://iotexscan.io/tx/0x9ce5f296e8c9b18609beab03bbe738847d51c5c9334c7f0b300773d1e1ff256b

3. Tax will not be charged if sender is bridge contract and the recipient is a contract **-> this should be correct.**

Could you also help provide some tx examples with contract sender/recipient?

Check this: https://iotexscan.io/tx/0x9ce5f296e8c9b18609beab03bbe738847d51c5c9334c7f0b300773d1e1ff256b
Smart Contract is multisig -> sent to address without charge!

**Comment by CoderZhi** [comment]
Crosschain IoTexShiba on IoTeX: [0xFb69f2C0d9C48564AeD32af1c6F342a036c94942](https://iotexscan.io/address/0xFb69f2C0d9C48564AeD32af1c6F342a036c94942)
Crosschain IoTexShiba on BSC: [0x52702a7301be185cc97bf3fe6d497a83e7772fde](https://bscscan.com/address/0x52702a7301be185cc97bf3fe6d497a83e7772fde)

let's try out this pair first @guo
