### ISSUE TITLE
Only received 0.2 IOTX on first use, not enough for one operation

### ISSUE THREAD

**Issue by sljeff** [iotubeproject/ioTube#255]
## Expected Behavior

Get 0.5 IOTX for the first time using ioTube.

## Current Behavior

1. Only got [0.2 IOTX](https://iotexscan.io/tx/77c59e99acfc77831585b07e6d86d3b7a4b26aa40a20a49eddd9c628bb162ae2).
2. The [`Approve`](https://iotexscan.io/tx/d2220268839fc083b83a4268168b0d3f0a33b7ce5f5987ec37a685886ab359b8) operation spent 0.08+ IOTX as GAS, I am unable to do the next operation (Unwrap).

## Possible Solution

Send 0.5 IOTX

## Steps to Reproduce

1. [Bridge](https://etherscan.io/tx/0x0a71d01366b273480fb8aa26fb435dba31d1234683a950ca1ff9a0a8bf46d6d9) CIOTX from ETH to IoTeX
2. Only got [0.2 IOTX](https://iotexscan.io/tx/77c59e99acfc77831585b07e6d86d3b7a4b26aa40a20a49eddd9c628bb162ae2)
3. [`Approve`](https://iotexscan.io/tx/77c59e99acfc77831585b07e6d86d3b7a4b26aa40a20a49eddd9c628bb162ae2) for `Unwrap` (2000 Gwei by default, using rabby wallet)
4. No enough gas to do `Unwrap` (If manually set below 1000 Gwei, it will fail)

## Context (Environment)

- Rabby wallet 0.92.76 Chrome ext
- My address: https://iotexscan.io/address/0xe02a52A553ACf14cD5552E53D48Dc0fC072978D8?format=0x

**Comment by guo** [comment]
sent 1 IOTX for your gas. enjoy!
https://iotexscan.io/tx/0x6c944e727afaef97bee0ac20185dbe7e5ec7941ad09454fea4d2f73a8a3dab5b

**Comment by sljeff** [comment]
> sent 1 IOTX for your gas. enjoy! https://iotexscan.io/tx/0x6c944e727afaef97bee0ac20185dbe7e5ec7941ad09454fea4d2f73a8a3dab5b

Thank you, my issue has been resolved.

However, the ioTube bridge page displays that anyone will receive 0.5 IOTX, perhaps this notification should be changed to 0.2 or the actual gift amount should be changed to 0.5.

Thank you for your work anyway.

**Comment by guo** [comment]
Thanks for the comment. We will make it clear.
