### ISSUE TITLE
New Token submission

### ISSUE THREAD

**Issue by xDollarFi** [iotubeproject/ioTube#35]
# ioTube Token submission

## Team / Developer name
MCN Ventures

## Token Symbol
MCN

## Token Name in full
MCN.VENTURES

## Link to the token icon
https://mcn.ventures/asset/mcn-logo-white-bg-200.png

## Short description of your project
MCN ventures is a decentralized venture fund combining VC efficiency with tokenomics bootstrapping community and fund growth.

## What is the native blockchain for your token
* [*] Ethereum
* [ ] Binance Smart Chain
* [ ] Polygon
* [ ] Huobi Eco Chain (coming soon)

## Token native contract address
Address: 0xd91e9a0fef7c0fa4ebdaf4d0acf55888949a2a9b

## Your project websites
- https://mcn.ventures/

## Your social channels
- Telegram:
- Twitter: https://twitter.com/MCNVentures
- Discord: https://discord.com/invite/Hh4BmZfEFa

## Select the tokens you want to bridge to IoTeX

* [x] Ethereum Token → IoTeX: <token contract address on Ethereum> 0xd91e9a0fef7c0fa4ebdaf4d0acf55888949a2a9b
* [ ] Binance Smart Chain Token → IoTeX: <token contract address on BSC>
* [ ] Polygon Token → IoTeX: <token contract address on Polygon>
* [ ] Huobi Eco Chain Token (coming soon) → IoTeX: <token contract address on HEC>

**Comment by guo** [comment]
Listed. Let's move to marketing team to follow up.
