### ISSUE TITLE
New Token submission CCS

### ISSUE THREAD

**Issue by Mentors4EDU** [iotubeproject/ioTube#48]
# ioTube Token submission

## Team / Developer name
CloutContracts

## Token Symbol
CCS

## Token Name in full
CloutContracts

## Link to the token icon
https://cloutcontracts.net

## Short description of your project
CloutContracts is the token behind a smart contracts platform for influencers and creators. It wants to be part of a high speed rollup layer that powers the next generation of blockchain developers.

## What is the blockchain (source blockchain) that your token is issued on

* [x] Ethereum  
* [ ] Binance Smart Chain
* [ ] Polygon
* [ ] IoTeX

https://cloutcontracts.net/explorer

## Token native contract address

Address: 0x1da4858ad385cc377165a298cc2ce3fce0c5fd31

## Your project websites

- https://cloutcontracts.net

## Your social channels

- Minds: http://www.minds.com/CloutContracts
- Steemit: https://steemit.com/@cloutcontracts
- BitClout: https://bitclout.com/u/CloutContracts
- Peepeth: https://peepeth.com/CloutContracts
- Reddit: https://www.reddit.com/r/CloutContracts/
- Discord: https://discord.com/invite/46nsUSqdfC
- Telegram: https://t.me/CloutContracts
    
## How would you like your token to be bridged?

* [x] Bridge Option 1. Create a crosschain token and bridge it to all different blockchains 
* [ ] Bridge Option 2. Just bridge my token to IoTeX (from source chain to IoTeX)

## What is the preferred name of your bridged token

* [x] the same as my token on source blockchain (Bridge option 1)
* [ ] C-token (denoting the crosschain version of the token) (Bridge Option 1)
* [ ] add a subfix denoting the source blockchain (```_b``` for bsc, ```_m``` for matic) (Bridge Option 2)
* [ ] other, please specify:

**Comment by guo** [comment]
Sorry for missing this request (buried in spam submissions). Could you please reach out to me on tg @qevanguo for more details of the token. Thanks!

Closing for now. Feel free to re-open it or submit a new one.

**Comment by Mentors4EDU** [comment]
> Sorry for missing this request (buried in spam submissions). Could you please reach out to me on tg @qevanguo for more details of the token. Thanks!
> 
> Closing for now. Feel free to re-open it or submit a new one.

Okay

**Comment by guo** [comment]
Let's go with option 1. option 2 is only for stable tokens and native coins. 

Please send $400 worth ETH or IOTX to 0x571e603e3B5c82Bd40998C538603dF4fb42bB051 for integration fee. and please send some CCS test token to the same address. 

Thanks!

**Comment by Mentors4EDU** [comment]
> Let's go with option 1. option 2 is only for stable tokens and native coins.
> 
> Please send $400 worth ETH or IOTX to 0x571e603e3B5c82Bd40998C538603dF4fb42bB051 for integration fee. and please send some CCS test token to the same address.
> 
> Thanks!

I believe the community team has done so. Please check.

**Comment by guo** [comment]
```
2022/01/05 13:11:24 Deploying crosschain token (0x1da4858ad385cc377165A298CC2CE3fce0C5fD31, 0x964F4f19Bc823E72cc1F806021937cfC06F63B45, Crosschain CloutContracts, CCCS, 0)
2022/01/05 13:11:26 Waiting token 0xf79deaBc1406a3AD07c70877fBaEb90777B77E68 deployment for 0x1da4858ad385cc377165A298CC2CE3fce0C5fD31 with tx 0x2096f0917eb1baf754de04a082d8d0a9c728b1662ebaa4f39641fd92138d8723
2022/01/05 13:11:26 Wait for 5s...
2022/01/05 13:11:31 Wait for 5s...
2022/01/05 13:15:21 Adding token f79deabc1406a3ad07c70877fbaeb90777b77e68 to token list 73ffdfc98983ad59fb441fc5fe855c1589e35b3e via tx 0x92400e75806257f218187fffbc9e8d172f72272761b7bc275a3c2017e1689ef0
2022/01/05 13:15:21 Wait for 5s...
2022/01/05 13:19:47 Deploying crosschain token (0x0000000000000000000000000000000000000000, 0x4799d57aBf5F12cA4eF5375c9dadF8fe7fA5A454, CloutContracts, CCS, 0)
2022/01/05 13:19:49 Waiting token 0x6f7320e66c89F512b5c7307e1f60A21D5297E0A1 deployment for 0x0000000000000000000000000000000000000000 with tx 0x5cf75ae3a3f34334493b211bcc786eec8e06b02b3707e182a225889cc11c1bba
2022/01/05 13:19:49 Wait for 5s...
2022/01/05 13:19:54 Wait for 5s...
2022/01/05 13:21:43 failed to estimate gas needed: execution simulation failed: status = 106
```

**Comment by guo** [comment]
C-Token on ETH: 0xf79deaBc1406a3AD07c70877fBaEb90777B77E68
TOKEN on IoTeX: 0x6f7320e66c89F512b5c7307e1f60A21D5297E0A1

**Comment by guo** [comment]
Update: still some issues on the frontend because no decimals function on the smart contract. working on it.

**Comment by anshuomomo** [comment]
closing as it is done.

**Comment by Mentors4EDU** [comment]
Hi, one more thing, can you verify the contract source code and ABI on Iotex as well?

**Comment by guo** [comment]
all good now. closing.
