### ISSUE TITLE
ForTube token

### ISSUE THREAD

**Issue by b1u3h4t** [iotubeproject/ioTube#52]
# ioTube Token submission

## Team / Developer name
ForTube

## Token Symbol
FOR

## Token Name in full
The Force Token

## Link to the token icon
https://imgur.com/a/Lv8Qaku

## Short description of your project
World's Top DeFi Lending Platform

## What is the blockchain (source blockchain) that your token is issued on

* [x] Ethereum  
* [x] Binance Smart Chain
* [x] Polygon
* [ ] IoTeX

## Token native contract address

Address: https://bscscan.com/token/0x658a109c5900bc6d2357c87549b651670e5b0539

## Your project websites

- https://for.tube

## Your social channels

- Telegram: https://t.me/ForTubeFi
- Twitter: https://twitter.com/ForTubeFi
- Discord:
    
## How would you like your token to be bridged?

* [x] Bridge Option 1. Create a crosschain token and bridge it to all different blockchains 
* [ ] Bridge Option 2. Just bridge my token to IoTeX (from source chain to IoTeX)

## What is the preferred name of your bridged token

* [x] the same as my token on source blockchain (Bridge option 1)
* [ ] C-token (denoting the crosschain version of the token) (Bridge Option 1)
* [ ] add a subfix denoting the source blockchain (```_b``` for bsc, ```_m``` for matic) (Bridge Option 2)
* [ ] other, please specify:

**Comment by guo** [comment]
Hello, thanks for submission. We are working on it now.

**Comment by guo** [comment]
deployed contract:
CFOR on bsc: 0x7e544f2fEDDc69b1cB12555779c824CFe100ee34
FOR on IoTeX: 0x0bDF82F276309E2efd4947Ee8E0A248b2726E8Df

[ ] add to dapp
[ ] add to validator config

**Comment by guo** [comment]
FOR is supported by ioTube now.
