### ISSUE TITLE
New Token submission - Bioshib

### ISSUE THREAD

**Issue by IoTexShiba** [iotubeproject/ioTube#71]
# ioTube Token submission

## Team / Developer name
IoTexShiba

## Token Symbol
BioShib

## Token Decimals
18

## Token Name in full
Baby IoTexShiba

## Link to the token icon
https://www.iotexshiba.io/wp-content/uploads/2021/11/bioshib200x.png

## Short description of your project

IotexShiba is a dual tokenomics ecosystem of the tokens IoShib and BioShib. It's a meme token with the goal to connect people and bring more awareness to the IoTex Ecosystem. Our native token IoShib is already well established and approved by IoTex Team and IoTex community. In order to continue to develop our goals, its from key importance to bridge our second token bioshib from binance smart chain to the IoTex Blockchain.

## What is the blockchain (source blockchain) that your token is issued on

Binance Smart Chain

## Token native contract address

Address: https://bscscan.com/token/0xab951271F025D93c278516e3d131e017e8a3089D

[## Your project websites]

- https://www.iotexshiba.io/

## Your social channels

- Telegram: https://t.me/iotexshiba
- Twitter: https://twitter.com/IoTexShiba
    
## How would you like your token to be bridged?

We would prefer Option 1 to further expand our reach and awareness.

* [x] Bridge Option 1. Create a crosschain token and bridge it to all different blockchains 
* [ ] Bridge Option 2. Just bridge my token to IoTeX (from source chain to IoTeX)

## What is the preferred name of your bridged token

* [ ] the same as my token on source blockchain (Bridge option 1)
* [x] C-token (denoting the crosschain version of the token) (Bridge Option 1)
* [ ] add a subfix denoting the source blockchain (```_b``` for bsc, ```_m``` for matic) (Bridge Option 2)
* [ ] other, please specify:

cbioshib

**Comment by IoTexShiba** [comment]
Please note, that bioshib has tax features in the smart contract. In the event of a listing on iotube we will exclude the bridge from fees and rewards. Bridge contract shouldn't copy the tax features and should be an erc20 standard contract only.

**Comment by guo** [comment]
Thanks for the submission!

Have you issued another token on IoTeX? Or you would like the BioShib token
to be bridged over IoTeX?

**Comment by IoTexShiba** [comment]
Dear Guo,

BioShib is the second token in our ecosystem and we want to bridge it to IoTex blockchain. 

We already have an established token on iotex: https://iotexscan.io/token/0x3ea683354bf8d359cd9ec6e08b5aec291d71d880

Since we want to integrate both tokens with our planned dapp, its crucial for us to bridge bioshib to iotex blockchain.

thanks and regards

Mike

**Comment by guo** [comment]
c-token on bsc: 0xa0CB9c8e470EC591dd7f5De650af9468EE6f7d5A
proxy token on iotex: 0xc1B58620aD839383c662BFe80dB4514344DeC6d7

- [ ] deploy tokens
- [ ] add to front end.

**Comment by guo** [comment]
```
2021/12/31 10:27:25 Deploying crosschain token 0xa0CB9c8e470EC591dd7f5De650af9468EE6f7d5A for 0xab951271F025D93c278516e3d131e017e8a3089D with tx 0xdc3e94bf2f74c17287385369330c6b59a4821ac34f7b29f36be7c7b8357a9a42
2021/12/31 10:27:25 Wait for 5s...
2021/12/31 10:28:36 Adding 0xa0CB9c8e470EC591dd7f5De650af9468EE6f7d5A to router via tx 0x5323f2a0e96821b799cff79786167636f5946563adbf9a6f3e77f884b716c87a
2021/12/31 10:28:36 Wait for 5s...
2021/12/31 10:28:41 Wait for 5s...
2021/12/31 10:29:47 Adding token a0cb9c8e470ec591dd7f5de650af9468ee6f7d5a to token list a6ae9312d0aa3cc74d969fcd4806d7729a321ee3 via tx 0xa529dad5897e31c8ef2007d93eedae9bbb760b9d8b1b522cb02b1ae4e63bb188
2021/12/31 10:29:47 Wait for 5s...
2021/12/31 10:30:59 Deploying crosschain token 0xc1B58620aD839383c662BFe80dB4514344DeC6d7 for 0x0000000000000000000000000000000000000000 with tx 0xb6746f42b97ea45784b9030a900a59e8bb2282a48e8ec9bc9050212f86627eef
2021/12/31 10:30:59 Wait for 5s...
2021/12/31 10:31:05 Wait for 5s...
2021/12/31 10:32:54 Adding token c1b58620ad839383c662bfe80db4514344dec6d7 to token list f0cb9bca0b74aa84804e0ede74ca6dd3f577d6ea via tx 0x505201cad0957e166d6229c09d2e646005acb2e49f7216c75f79daece3359dab
```

**Comment by IoTexShiba** [comment]
Thank you for the work you've done so far, looking good! What is the ETA for having the token available on the frondend?

**Comment by IoTexShiba** [comment]
@guo thanks for adding bioshib to the bridge. Its working so far, but there is one major issue. We can't deposit more than 1m token at once into the contract. Can you look into it? Our max supply is quite large. Would be good if the limit would be removed.

**Comment by guo** [comment]
Increased to 100m now.

**Comment by guo** [comment]
Please give  it a test too. Thanks

**Comment by IoTexShiba** [comment]
@guo thanks for the fast response. Its working on the BSC blockchain, but on IOTEX side its still capped to 1m right now. Since our total supply is 100 billion and I need to move 40b for staking on iotex network, it would be great if the amount could be increased to 1b per deposit on bsc and iotex side.

**Comment by guo** [comment]
ok. let me take a look

**Comment by guo** [comment]
updated too

**Comment by IoTexShiba** [comment]
@guo thanks its working now. Thanks for your support. Anything else need to be done? Otherwise I would close the case.

**Comment by IoTexShiba** [comment]
@guo one more question. Right now I dont see any option to unwrap the tokens. They get returned to BSC as C-Bioshib tokens, but the unwrap function don't seem to work on iotube. Therefore I've added a bioshib-c-bioshib liquidity pool on binance, but in the long run, if we can't unwrap, c-bioshib would loose peg against bioshib. Any solution to that?

**Comment by guo** [comment]
yes. Currently, bridging back, users get CBioshib. Unwrapping process cannot be automatically done at this moment. In the next version of iotube, it may be supported because cross chain smart contract call will be supported.

**Comment by guo** [comment]
closing as it is done.
