### ISSUE TITLE
New Token submission

### ISSUE THREAD

**Issue by Texmentor** [iotubeproject/ioTube#74]
# ioTube Token submission - IotexPad

## Team / Developer name
Tex Wright

## Token Symbol
TEX

## Token Decimals
18

## Token Name in full
IotexPad

## Link to the token icon
https://iotexpad.network/iotexpadICON.png

## Short description of your project
IotexPad is the first Launchpad and Incubator Native to the IoTeX Network built for the IoTeX Community. IotexPad is an accelerator and incubator for projects connecting the investors with developers.

## What is the blockchain (source blockchain) that your token is issued on

* [ ] Ethereum  
* [ ] Binance Smart Chain
* [ ] Polygon
* [yes] IoTeX

## Token native contract address

Address: io1qjv68myk2ymtagq7gdgpzw3pq4ey0pwuu8z7pj

## Your project websites

- https://iotexpad.network

## Your social channels

- Telegram: https://t.me/iotexpad
- Twitter: https://itwitter.com/iotexpad
- Medium: iotexpad.medium.com
    
## How would you like your token to be bridged?

* [yes ] Bridge Option 1. Create a crosschain token and bridge it to all different blockchains ( We want to bridge to BSC)
* [] Bridge Option 2. Just bridge my token to IoTeX (from source chain to IoTeX)

## What is the preferred name of your bridged token

* [TEX ] the same as my token on source blockchain (Bridge option 1)
* [ ] C-token (denoting the crosschain version of the token) (Bridge Option 1)
* [] add a subfix denoting the source blockchain (```_b``` for bsc, ```_m``` for matic) (Bridge Option 2)
* [ ] other, please specify:

**Comment by guo** [comment]
CTEX on IoTeX: 0x28873cEA8c26F603b15937f9985A888C5DA5Fd90
TEX on BSC: 0x049Dd7532148826CdE956c7B45fec8c30b514052

- [ ] deploy smartcontracts
- [ ]  add to witness 
- [ ] add to web

**Comment by guo** [comment]
this has been added to iotube. enjoy!
