### ISSUE TITLE
New Token submission - FRST

### ISSUE THREAD

**Issue by mrcryptofrosty** [iotubeproject/ioTube#78]
# ioTube Token submission

## Team / Developer name: 
Joseph Merheb
Amrita Tiwani
Francy 
Lara Ghattas
...

## Token Symbol: FRST
...

## Token Decimals: 18
... 

## Token Name in full: FRST
...

## Link to the token icon
https://raw.githubusercontent.com/mrcryptofrosty/FROSTY-Whitepaper/main/images/Frosty(200x200).png

## Short description of your project
Frosty aim to be a supply chain of arts and 3D models for the metaverse.

## What is the blockchain (source blockchain) that your token is issued on

* [ ] Ethereum  
* [x] Binance Smart Chain
* [ ] Polygon
* [ ] IoTeX

## Token native contract address

Address: 0x624b853bb7359061af85f8fe47318c31a866a054

## Your project websites

- https://frosty.app

## Your social channels

- Telegram: https://t.me/Frosty_Announcements
- Twitter: https://twitter.com/Frosty_DeFi
- Discord: https://discord.gg/ph3qN7UhWe
    
## How would you like your token to be bridged?

* [x ] Bridge Option 1. Create a crosschain token and bridge it to all different blockchains 
* [ ] Bridge Option 2. Just bridge my token to IoTeX (from source chain to IoTeX)

## What is the preferred name of your bridged token

* [ x] the same as my token on source blockchain (Bridge option 1)
* [ ] C-token (denoting the crosschain version of the token) (Bridge Option 1)
* [ ] add a subfix denoting the source blockchain (```_b``` for bsc, ```_m``` for matic) (Bridge Option 2)
* [ ] other, please specify:

**Comment by guo** [comment]
please send a few test tokens to 0x571e603e3B5c82Bd40998C538603dF4fb42bB051 or io12u0xq03mtjpt6sye33fcvq7lf76zhvz3yvt8q0

**Comment by guo** [comment]
Do you have any places to verify the token address on your website?

**Comment by guo** [comment]
if you have CMC or coingecko profile with token address listed, please share. it is useful to verify.

**Comment by mrcryptofrosty** [comment]
We will add it shortly, currently you can verify it by connecting to https://www.frosty.app/frostboard

**Comment by mrcryptofrosty** [comment]
How many tokens are required? We have a total supply of 10K tokens where 4400 are in circulations.
How can we deploy our token to IoTx network as well for cross-chaining?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by guo** [comment]
> How many tokens are required? We have a total supply of 10K tokens where 4400 are in circulations.
$1-$10 worth token is good enough.
> How can we deploy our token to IoTx network as well for cross-chaining?
We will deploy the token. 
A quick question, do you have special requirement for your bridged token than standard xrc20/bep20/erc20?

**Comment by mrcryptofrosty** [comment]
Dear IoTube team,

Did you received the tokens?

Best Regards.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by guo** [comment]
still actively requesting?
