### ISSUE TITLE
my bnb stuck on iotube between trustwallet and iopay

### ISSUE THREAD

**Issue by ahldo13** [iotubeproject/ioTube#80]
This is **ONLY** used for reporting bugs.

## Expected Behavior
 my bnb got stuck
on iotube platform
## Possible Solution

please complete my transaction to my iopay wallet or refund it to my trustwallet
## Steps to Reproduce

1.i send my bnb to iopay
2.iopay recieve a small amount of iotx
3.i send my iotx to binance
4.but my bnb stuck on iotube 

## Context (Environment)
 you stolen my bnb.
 do something
thief platform

**Comment by guo** [comment]
please send to support@iotex.io for help.
