### ISSUE TITLE
my bnb got stuck on iotube platform

### ISSUE THREAD

**Issue by ahldo13** [iotubeproject/ioTube#82]
This is **ONLY** used for reporting bugs.

i already sent my problem but no one.response.

## Expected Behavior
got stuck.on iotube platform everytime i look on my wallet its show the value of my assets

## Current Behavior
please move it on my iopay wallet

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jrynkiew** [comment]
Please note that this channel of communication is only to report bugs in the code of the product. In your case, this is a bit different, as it's a usability issue. These issues sometimes occur. Please report this and any other issue you have with our products via e-mail to support@iotex.io

**Comment by jrynkiew** [comment]
P.S. I looked in the IoTeX ioTube Explorer at https://iotube.org/explorer#iotex and I could not find a failed transaction. Make sure you include your initial transaction hash of your interaction with the ioTube in your communication with the support team.
