### ISSUE TITLE
New Token submission - Shibex

### ISSUE THREAD

**Issue by yosefede06** [iotubeproject/ioTube#86]
# ioTube Token submission

Please read the token submission guide here: https://docs.iotube.org/introduction/token-submission

## Team / Developer name
Rapahael Bohbot (CEO)
Yosef Edery (CTO)
Ilan Benhamou (Game Developer)
Nathanel Bohbot (COO)
Salome Moati (Community Manager)

## Token Symbol
SHIBX

## Token Decimals
18

## Token Name in full
Shibex

## Link to the token icon
https://ipfs.io/ipfs/QmVrp6adhptZfNhkLazfkyPLwMnL8EVULHPsfhGXcnPEJC

## Short description of your project
Shibex is a Gamefi platform where SHIBX is the token that allow players to play and bet their SHIBX tokens against other players. the platform will lunch Arcade games regularly and SHIBX will be the utility token for all the games. The game economics is a new mechanism called "play2burn" where a part of the tokens that bet in the games are burn until the token get 20% out of the supply, then the tokens will go back to the holders and liquidity providing.
## What is the blockchain (source blockchain) that your token is issued on
IoTeX

## Token native contract address explorer link

Address:
https://iotexscan.io/address/io1swzq8crn57t3ngyj0gtxgt98mnwxg274knr566?format=0x#code
## Your project websites

www.shibex.game
https://shibex-soldiers.web.app

## Your social channels

- Telegram: https://t.me/ShibexToken
- Twitter: https://twitter.com/ShibexSoldiers
- Discord:

## Verification of the token

Please provide the verification of your token in one of the following ways.

* [x] Token address on your website. Please specify the link.
https://www.shibex.game
* [ ] CMC / Coingecko profile link with token contract address and link to website/social

## Send test tokens 

Please send a few test tokens ($1-$10 worth) to our wallet address: `0x571e603e3B5c82Bd40998C538603dF4fb42bB051`.

## Integration fee 

Please send the payment to `0x571e603e3B5c82Bd40998C538603dF4fb42bB051` or `io12u0xq03mtjpt6sye33fcvq7lf76zhvz3yvt8q0` and post your txn link here.
https://polygonscan.com/tx/0x3189665b15a7156eef51e9ca2cfff8be3287c2eb2c041627adbf62fcb1d8d2e2

**Comment by guo** [comment]
Matic: 0x3Fe5Dda8d6265Da3c9dE0056dCabB5Ae518fF78b
C-Token: 0x37de3C10dF4d49a45fDaA7C2a5c5E1c6DD653491

pending add to UI.

**Comment by guo** [comment]
live now.
https://twitter.com/iotube_org/status/1491317359679737857
