### ISSUE TITLE
The source code is recompiled and matches the one that is deployed on-chain.

### ISSUE THREAD

**Issue by sukruarc** [iotubeproject/ioTube#91]
The source code is recompiled and matches the one that is deployed on-chain.

- A green tick means that the contract's code is verified.
- For example Tether, https://etherscan.io/address/0xdac17f958d2ee523a2206206994597c13d831ec7#code

Thank you for your hard work.
Cheers!

__Originally posted by @kiok46 in https://github.com/jay-bch/smartbch-explorer/issues/3__

**Comment by guo** [comment]
why this issue appear here? it seems on another repo.
